app:
  name: "go-web"
  version: "0.1.0"
  mode: "dev"  # dev, test, prod

http:
  host: "0.0.0.0"
  port: 8082     # 改为不同的端口
  engine: "gin"
  readTimeout: 10s
  writeTimeout: 10s
  maxHeaderBytes: 1048576  # 1MB
  maxBodySize: 4194304    # 4MB

jwt:
  secret: "go-web-secret-key-please-change-in-production"
  accessExpire: 7200       # 访问令牌过期时间(秒)，默认2小时
  refreshExpire: 604800    # 刷新令牌过期时间(秒)，默认7天

database:
  driver: "sqlite"  # 修改为sqlite，与代码匹配
  dsn: "go-web.db"
  maxOpenConns: 100
  maxIdleConns: 10
  connMaxLifetime: 3600s
  logLevel: "info"

log:
  level: "info"  # debug, info, warn, error
  format: "text"  # text, json
  outputPath: "stdout"  # 改为输出到控制台

cache:
  type: "memory"  # memory, redis, file
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  prefix: "go-web:"
  filePath: "cache"

applications:
  # 启用的应用
  enabled:
    - admin
    - api
    - cli
  
  # 管理后台应用
  admin:
    prefix: "/admin"
    auth: true
    middleware:
      - auth
      - logger
    title: "Go-Web后台管理系统"
  
  # API应用
  api:
    prefix: "/api"
    version: "v1"
    rate_limit: 100
    cors: true
    middleware:
      - cors
      - rate_limit
      - logger
  
  # CLI应用
  cli:
    commands:
      - migrate
      - seed
      - cache:clear
      - make:model
      - make:controller 